// codergb-hub-profile/src/views/detail/momentDetail/MomentDetail.vue
<template>
  <div class="moment-container">
    <el-card v-loading="loading">
      <el-form v-if="detail">
        <el-row>
          <el-col :span="24">
            <el-form-item label="标题：">
              <span class="title">{{ detail.title }}</span>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <el-form-item label="内容">
              <span class="content">{{ detail?.content }}</span>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row :gutter="24">
          <el-col :span="12">
            <el-form-item label="创建时间">{{
              moment(detail.createTime).format('YYYY-MM-DD HH:mm')
            }}</el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="创建人">{{ detail.user.userName }}</el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </el-card>
    <el-card>
      <el-tabs v-model="activeName">
        <el-tab-pane label="评论" name="comment">
          <Comment />
        </el-tab-pane>
        <el-tab-pane label="关联视频" name="associate-video">
          <Video />
        </el-tab-pane>
      </el-tabs>
    </el-card>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import { useRoute } from 'vue-router';

import Comment from './childCpn/comment/Comment.vue';
import Video from './childCpn/video/Video.vue';
import { IMoment } from '@/types/moment';
import { getMomentDetail } from '@/network/moment';
import { IResponseType } from '@/types/responseType';
import moment from 'moment';
const route = useRoute();
const detail = ref<IMoment | null>(null);
const loading = ref<boolean>(false);
const { id } = route.params;
const activeName = 'comment';
loading.value = true;
getMomentDetail<IResponseType<IMoment>>(id as string).then((res) => {
  if (res.status === 200) {
    loading.value = false;
    detail.value = res.data;
  }
});
</script>
<style scoped lang="less">
.moment-container {
  .el-card {
    margin: 0 0 15px 0;
  }
}
</style>

// codergb-hub-client/src/components/content/detail/momentDetail/index.tsx
import React, { memo, FC, ReactElement, useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { MomentDetailWrapper } from './style';
import { getMomentDetail } from '../../../../network/moment';
import { IMoment } from '../../../../types/moment';
import { IResponseType } from '../../../../types/responseType';
import Publish from './childCpn/publish';
const MomentDetail: FC = (): ReactElement => {
  const location = useLocation();
  const { id } = location.state;
  const [moment, setMoment] = useState<IMoment>();
  useEffect(() => {
    getMomentDetail<IResponseType<IMoment>>(id).then((data) => {
      if (data.status === 200) {
        setMoment(data.data);
      }
    });
  }, [id]);
  return (
    <MomentDetailWrapper>
      <div className="moment-header">
        {moment && (
          <div className="left-container">
            <img src={moment?.user.avatarUrl} />
          </div>
        )}
        {moment && (
          <div className="right-container">
            <p className="user-name">{moment.user.userName}</p>
            <p className="title">{moment.title}</p>
            <p className="content">{moment.content}</p>
            <div className="img-container">
              <img src={moment.video.picUrl} />
            </div>
          </div>
        )}
      </div>
      <div className="moment-body">{moment && <Publish id={moment.id} />}</div>
    </MomentDetailWrapper>
  );
};
export default memo(MomentDetail);
